[package]
name = "core"
version = "0.0.1"
authors = ["azhi <astzhe@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
rand = "0.3"
time = "0.1"

[dependencies.anymap]
version = "0.10.3"
features = ["clone"]
